CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(255),
    description LONGTEXT,
    color VARCHAR(255),
    material VARCHAR(255)
);
